# Generated by Django 5.0.6 on 2024-05-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_alter_article_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="description",
            field=models.TextField(
                default="", help_text="Used in alt attribute to describe image."
            ),
            preserve_default=False,
        ),
    ]
