# Generated by Django 5.0.6 on 2024-05-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="photo_description",
            field=models.TextField(
                default="",
                help_text="Used in alt attribute to describe image in context of the article.",
            ),
            preserve_default=False,
        ),
    ]
