# Generated by Django 5.0.6 on 2024-06-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_article_photo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_decorative',
            field=models.BooleanField(default=False, help_text='Is the image decorative in this context?'),
        ),
        migrations.AlterField(
            model_name='article',
            name='photo_description',
            field=models.TextField(blank=True, help_text='Used in alt attribute to describe image in context of the article.', null=True),
        ),
    ]
