# Generated by Django 5.0.6 on 2024-05-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0006_article_is_decorative_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialicon",
            name="linktext",
            field=models.CharField(
                default="", help_text="Name of the social media.", max_length=100
            ),
            preserve_default=False,
        ),
    ]
