# Generated by Django 5.0.6 on 2024-05-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0007_socialicon_linktext"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("es", "Español")],
                default="en",
                max_length=2,
            ),
        ),
    ]
